export default function Feed() {
  const alerts = [
    {
      date: "Mar 19, 2026",
      ticker: "SMCI",
      headline: "CEO Charles Liang sold $2.1M in stock",
      detail: "First sale in 14 months, outside scheduled plan. Historical pattern: avg −12% over 30 days.",
      severity: "HIGH",
    },
    {
      date: "Feb 28, 2026",
      ticker: "NVDA",
      headline: "CFO filed Form 4 — routine scheduled sale",
      detail: "Part of 10b5-1 plan. No anomaly detected. Monitoring continues.",
      severity: "LOW",
    },
    {
      date: "Jan 14, 2026",
      ticker: "TSLA",
      headline: "Board member purchased 50,000 shares",
      detail: "Insider buying is generally a positive signal. No action recommended.",
      severity: "INFO",
    },
  ];

  const colors: Record<string, string> = {
    HIGH: "text-red-400 border-red-900 bg-red-950/20",
    LOW: "text-zinc-400 border-zinc-800 bg-zinc-900/20",
    INFO: "text-green-400 border-green-900 bg-green-950/20",
  };

  return (
    <main className="min-h-screen flex flex-col items-center px-6 py-16 gap-6 max-w-lg mx-auto">
      <div className="w-full flex items-center gap-2">
        <span className="text-red-500 text-xl">🚨</span>
        <h1 className="text-xl font-bold">911Stock — Alert Feed</h1>
      </div>
      <p className="text-xs text-zinc-600 w-full">
        Autonomous alerts generated by your stock guardian
      </p>
      {alerts.map((alert, i) => (
        <div key={i} className={`w-full border rounded-lg p-4 ${colors[alert.severity]}`}>
          <div className="flex items-center justify-between mb-1">
            <span className="font-bold text-sm">{alert.ticker}</span>
            <span className="text-xs opacity-60">{alert.date}</span>
          </div>
          <p className="text-sm font-medium mb-1">{alert.headline}</p>
          <p className="text-xs opacity-70">{alert.detail}</p>
        </div>
      ))}
    </main>
  );
}
